version: '3.8'
services:
    capital-gains-php:
        container_name: capital-gains-php
        build:
            context: ./
            dockerfile: images/php/Dockerfile
        ports:
            - "8080:80"
        volumes:
            - ./config/apache/default.conf:/etc/apache2/sites-enabled/default.conf
            - type: bind
              source: ./src
              target: /var/www/html
volumes:
    src: